name: Kirpal Demian
firstname: Kirpal
description: >-
  I am a software engineer. I really enjoy building solid mobile apps with fantastic user 
  experiences. I also like analyzing and connecting data, and working with maps. Outside of 
  computers, I love distance running, hiking, cross-country skiing, and generally being in the 
  woods. Right now, I'm trying to find a way to use my skills to fight climate change or increase 
  global literacy and communication. I really haven't focused in on a specific problem and solution,
  but I'm always down to talk about it, so please reach out!

url: "https://kirp.al"
github_username:  kirpal

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"